### ISSUE TITLE
C and \delta

### ISSUE THREAD

**Issue by yuzhenmao** [zjiayao/fifa-iclr23#2]
Hi jiayao,

Thanks for sharing the code! I notice that in the current version, the hyper-parameters C and \delta in Eq. 4 of the original paper is not defined in the sweep config file. How to decide these hyper-parameters? Thanks!

**Comment by zjiayao** [comment]
Hey Zhenmao,

Thanks for your interest in the code! Sorry for the confusion, as you have probably already figured it out, $C$ is labelled as `max_m` and $\delta$'s are labelled as `d0m` (and its friends) in the config.

Please feel free to open another issue if you have any questions.

**Comment by yuzhenmao** [comment]
Thanks!
